export type SurahMeta = {
  number: number
  name: string
  ayahs: number
  /** 'M' = مكية, 'D' = مدنية */
  type: 'M' | 'D'
}

export const SURAHS: SurahMeta[] = [
  { number: 1, name: 'الفاتحة', ayahs: 7, type: 'M' },
  { number: 2, name: 'البقرة', ayahs: 286, type: 'D' },
  { number: 3, name: 'آل عمران', ayahs: 200, type: 'D' },
  { number: 4, name: 'النساء', ayahs: 176, type: 'D' },
  { number: 5, name: 'المائدة', ayahs: 120, type: 'D' },
  { number: 6, name: 'الأنعام', ayahs: 165, type: 'M' },
  { number: 7, name: 'الأعراف', ayahs: 206, type: 'M' },
  { number: 8, name: 'الأنفال', ayahs: 75, type: 'D' },
  { number: 9, name: 'التوبة', ayahs: 129, type: 'D' },
  { number: 10, name: 'يونس', ayahs: 109, type: 'M' },
  { number: 11, name: 'هود', ayahs: 123, type: 'M' },
  { number: 12, name: 'يوسف', ayahs: 111, type: 'M' },
  { number: 13, name: 'الرعد', ayahs: 43, type: 'D' },
  { number: 14, name: 'إبراهيم', ayahs: 52, type: 'M' },
  { number: 15, name: 'الحجر', ayahs: 99, type: 'M' },
  { number: 16, name: 'النحل', ayahs: 128, type: 'M' },
  { number: 17, name: 'الإسراء', ayahs: 111, type: 'M' },
  { number: 18, name: 'الكهف', ayahs: 110, type: 'M' },
  { number: 19, name: 'مريم', ayahs: 98, type: 'M' },
  { number: 20, name: 'طه', ayahs: 135, type: 'M' },
  { number: 21, name: 'الأنبياء', ayahs: 112, type: 'M' },
  { number: 22, name: 'الحج', ayahs: 78, type: 'D' },
  { number: 23, name: 'المؤمنون', ayahs: 118, type: 'M' },
  { number: 24, name: 'النور', ayahs: 64, type: 'D' },
  { number: 25, name: 'الفرقان', ayahs: 77, type: 'M' },
  { number: 26, name: 'الشعراء', ayahs: 227, type: 'M' },
  { number: 27, name: 'النمل', ayahs: 93, type: 'M' },
  { number: 28, name: 'القصص', ayahs: 88, type: 'M' },
  { number: 29, name: 'العنكبوت', ayahs: 69, type: 'M' },
  { number: 30, name: 'الروم', ayahs: 60, type: 'M' },
  { number: 31, name: 'لقمان', ayahs: 34, type: 'M' },
  { number: 32, name: 'السجدة', ayahs: 30, type: 'M' },
  { number: 33, name: 'الأحزاب', ayahs: 73, type: 'D' },
  { number: 34, name: 'سبأ', ayahs: 54, type: 'M' },
  { number: 35, name: 'فاطر', ayahs: 45, type: 'M' },
  { number: 36, name: 'يس', ayahs: 83, type: 'M' },
  { number: 37, name: 'الصافات', ayahs: 182, type: 'M' },
  { number: 38, name: 'ص', ayahs: 88, type: 'M' },
  { number: 39, name: 'الزمر', ayahs: 75, type: 'M' },
  { number: 40, name: 'غافر', ayahs: 85, type: 'M' },
  { number: 41, name: 'فصلت', ayahs: 54, type: 'M' },
  { number: 42, name: 'الشورى', ayahs: 53, type: 'M' },
  { number: 43, name: 'الزخرف', ayahs: 89, type: 'M' },
  { number: 44, name: 'الدخان', ayahs: 59, type: 'M' },
  { number: 45, name: 'الجاثية', ayahs: 37, type: 'M' },
  { number: 46, name: 'الأحقاف', ayahs: 35, type: 'M' },
  { number: 47, name: 'محمد', ayahs: 38, type: 'D' },
  { number: 48, name: 'الفتح', ayahs: 29, type: 'D' },
  { number: 49, name: 'الحجرات', ayahs: 18, type: 'D' },
  { number: 50, name: 'ق', ayahs: 45, type: 'M' },
  { number: 51, name: 'الذاريات', ayahs: 60, type: 'M' },
  { number: 52, name: 'الطور', ayahs: 49, type: 'M' },
  { number: 53, name: 'النجم', ayahs: 62, type: 'M' },
  { number: 54, name: 'القمر', ayahs: 55, type: 'M' },
  { number: 55, name: 'الرحمن', ayahs: 78, type: 'D' },
  { number: 56, name: 'الواقعة', ayahs: 96, type: 'M' },
  { number: 57, name: 'الحديد', ayahs: 29, type: 'D' },
  { number: 58, name: 'المجادلة', ayahs: 22, type: 'D' },
  { number: 59, name: 'الحشر', ayahs: 24, type: 'D' },
  { number: 60, name: 'الممتحنة', ayahs: 13, type: 'D' },
  { number: 61, name: 'الصف', ayahs: 14, type: 'D' },
  { number: 62, name: 'الجمعة', ayahs: 11, type: 'D' },
  { number: 63, name: 'المنافقون', ayahs: 11, type: 'D' },
  { number: 64, name: 'التغابن', ayahs: 18, type: 'D' },
  { number: 65, name: 'الطلاق', ayahs: 12, type: 'D' },
  { number: 66, name: 'التحريم', ayahs: 12, type: 'D' },
  { number: 67, name: 'الملك', ayahs: 30, type: 'M' },
  { number: 68, name: 'القلم', ayahs: 52, type: 'M' },
  { number: 69, name: 'الحاقة', ayahs: 52, type: 'M' },
  { number: 70, name: 'المعارج', ayahs: 44, type: 'M' },
  { number: 71, name: 'نوح', ayahs: 28, type: 'M' },
  { number: 72, name: 'الجن', ayahs: 28, type: 'M' },
  { number: 73, name: 'المزمل', ayahs: 20, type: 'M' },
  { number: 74, name: 'المدثر', ayahs: 56, type: 'M' },
  { number: 75, name: 'القيامة', ayahs: 40, type: 'M' },
  { number: 76, name: 'الإنسان', ayahs: 31, type: 'D' },
  { number: 77, name: 'المرسلات', ayahs: 50, type: 'M' },
  { number: 78, name: 'النبأ', ayahs: 40, type: 'M' },
  { number: 79, name: 'النازعات', ayahs: 46, type: 'M' },
  { number: 80, name: 'عبس', ayahs: 42, type: 'M' },
  { number: 81, name: 'التكوير', ayahs: 29, type: 'M' },
  { number: 82, name: 'الانفطار', ayahs: 19, type: 'M' },
  { number: 83, name: 'المطففين', ayahs: 36, type: 'M' },
  { number: 84, name: 'الانشقاق', ayahs: 25, type: 'M' },
  { number: 85, name: 'البروج', ayahs: 22, type: 'M' },
  { number: 86, name: 'الطارق', ayahs: 17, type: 'M' },
  { number: 87, name: 'الأعلى', ayahs: 19, type: 'M' },
  { number: 88, name: 'الغاشية', ayahs: 26, type: 'M' },
  { number: 89, name: 'الفجر', ayahs: 30, type: 'M' },
  { number: 90, name: 'البلد', ayahs: 20, type: 'M' },
  { number: 91, name: 'الشمس', ayahs: 15, type: 'M' },
  { number: 92, name: 'الليل', ayahs: 21, type: 'M' },
  { number: 93, name: 'الضحى', ayahs: 11, type: 'M' },
  { number: 94, name: 'الشرح', ayahs: 8, type: 'M' },
  { number: 95, name: 'التين', ayahs: 8, type: 'M' },
  { number: 96, name: 'العلق', ayahs: 19, type: 'M' },
  { number: 97, name: 'القدر', ayahs: 5, type: 'M' },
  { number: 98, name: 'البينة', ayahs: 8, type: 'D' },
  { number: 99, name: 'الزلزلة', ayahs: 8, type: 'D' },
  { number: 100, name: 'العاديات', ayahs: 11, type: 'M' },
  { number: 101, name: 'القارعة', ayahs: 11, type: 'M' },
  { number: 102, name: 'التكاثر', ayahs: 8, type: 'M' },
  { number: 103, name: 'العصر', ayahs: 3, type: 'M' },
  { number: 104, name: 'الهمزة', ayahs: 9, type: 'M' },
  { number: 105, name: 'الفيل', ayahs: 5, type: 'M' },
  { number: 106, name: 'قريش', ayahs: 4, type: 'M' },
  { number: 107, name: 'الماعون', ayahs: 7, type: 'M' },
  { number: 108, name: 'الكوثر', ayahs: 3, type: 'M' },
  { number: 109, name: 'الكافرون', ayahs: 6, type: 'M' },
  { number: 110, name: 'النصر', ayahs: 3, type: 'D' },
  { number: 111, name: 'المسد', ayahs: 5, type: 'M' },
  { number: 112, name: 'الإخلاص', ayahs: 4, type: 'M' },
  { number: 113, name: 'الفلق', ayahs: 5, type: 'M' },
  { number: 114, name: 'الناس', ayahs: 6, type: 'M' },
]

export const BISMILLAH = 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ'

/**
 * The quran-uthmani edition prefixes the bismillah onto the first ayah
 * of every surah except Al-Fatiha (1) and At-Tawbah (9). Strip it so we
 * can render it separately as a centered header line, like a real mushaf.
 */
export function stripBismillah(text: string, surah: number, numberInSurah: number): string {
  if (numberInSurah !== 1 || surah === 1 || surah === 9) return text
  // Find the end of the bismillah ("...الرحيم") near the start of the text.
  const match = text.match(/(حِيمِ|حِیمِ)/)
  if (match && match.index !== undefined && match.index < 60) {
    return text.slice(match.index + match[1].length).trimStart()
  }
  return text
}
